name: Daily Bilibili Scraper

on:
  schedule:
    - cron: '0 0 * * *' # 每天 00:00 UTC（北京时间 08:00）
    - cron: '0 12 * * *' # 每天 12:00 UTC（北京时间 20:00）
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest
    environment: github-pages
    steps:
      - uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run scraper
        run: python main.py

      - name: Deploy via GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.WeeklyAVideoToken }}
          publish_dir: ./output
