name: Daily Bilibili Scraper

on:
  schedule:
    - cron: '0 0 * * *'    # 每天 00:00 UTC（北京时间 08:00）
    - cron: '0 12 * * *'   # 每天 12:00 UTC（北京时间 20:00）
  workflow_dispatch:       # 允许手动触发

jobs:
  scrape:
    runs-on: ubuntu-latest
    environment: github-pages

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Cache pip
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          if [ -f requirements.txt ]; then
            pip install --upgrade pip
            pip install -r requirements.txt
          fi

      - name: Run scraper
        run: python main.py

      - name: Deploy via GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.WeeklyAVideoToken }}
          publish_dir: ./output
